name: neuro_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0=mkl
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  #libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libsodium=1.0.18
  - llvm-openmp=14.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openssl=3.3.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - readline=8.2
  - scipy=1.11.4
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.11.0
  - xz=5.4.5
  - zeromq=4.3.5
  - zlib=1.2.13
